import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import {AppProvider} from "@/components/AppContext"
import Header from "@/components/layout/Header";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"] , weight:['400','500','700']});

export const metadata: Metadata = {
  title: "MEGA PIZZA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4 ">
          <AppProvider>
          <Header />
          {children}
          <footer className="border-t p-8 text-center mt-6 text-gray-500">
          &copy; MalLem 2024 All rights reserved
          </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
